create table teachers
(
    ID         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName  varchar(255) NOT NULL,
    lastName   varchar(255) NOT NULL,
    age        int          not null check ( age > 6 ),
    experience int          not null check ( experience > 3 ),
    subject    varchar(255) NOT NULL
);

create table students
(
    ID        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName varchar(255) NOT NULL,
    lastName  varchar(255) NOT NULL,
    age       int          not null check ( age > 6 ),
    grade     int          not null check ( grade < 12 ),
    teacherId int,
    FOREIGN KEY (teacherId) REFERENCES teachers (Id) ON DELETE SET NULL
);